# This is the Wireless Redstone main configuration file.
# If you want to modify some of these lines, I highly recommend you to read this page : http://dev.bukkit.org/server-mods/wireless-redstone/pages/setup/configuration/

# Corresponds to the language used by the plugin. In order to get it working, you must have the corresponding file <language>.yml in the folder strings/
Language: en

# Set this value to true if you want the log in the console to be written with colors (it's easier to see what's wrong)
ColourfulLogging: true

# If you don't want to be spammed with a message telling you that an amazing new release with new great functionnalities has been released, then set it to false.
CheckForUpdates: false

# If true, then the plugin uses a database to store the channels.
UseSQL: true

# If you want to this plugin work, you should not set this value to false
cancelChunkUnloads: true

# Correspond to the radius where the chunk won't be unloaded around the wireless sign
cancelChunkUnloadRange: 4

# You have Vault but for any reason you don't want to use it? Set this value to false
UseVault: true

# Silent mode, don't send when you don't have permission (only on commands). Great for themparks
SilentMode: false

# Debug Mode, don't activate it if you're not a tester or a developper
DebugMode: false

# This value can be set to false, because some people can create signs with a command and destroy them to get free signs.
DropSignWhenBroken: true

# Time in ms.
InteractTransmitterTime: 1000

# Time in seconds.
CacheRefreshFrequency: 150