name: WirelessRedstone
main: net.licks92.WirelessRedstone.WirelessRedstone
website: http://dev.bukkit.org/server-mods/wireless-redstone/
author: licks92
version: 1.6b
description: A plugin for Bukkit that makes Wireless Redstone Connections! Original project by Wmisiedjan
softdepend: [Vault]
loadbefore: [Vault]
commands:
   wirelessredstone:
      aliases: [wr, wredstone, wifi]
      description: WirelessRedstone menu
      usage: |
             Example: /<command>
   wrhelp:
      description: WirelessRedstone help menu
      usage: |
             Example: /<command>
   wrt:
      aliases: [wrtransmitter, createtransmitter, ct]
      description: Creates a transmitter sign with given channel
      usage: |
             Example: /<command> Channel1
   wrr:
      aliases: [wrreceiver, createreceiver, cr]
      description: Creates a receiver sign with given channel
      usage: |
             Example: /<command> Channel1
   wrs:
      aliases: [wrscreen, createscreen, cs]
      description: Creates a screen sign with given channel
      usage: |
             Example: /<command> Channel1
   wrr:
      aliases: [wrreceiver, createreceiver, cr]
      description: Creates a receiver sign with given channel
      usage: |
             Example: /<command> Channel1
   wri:
      aliases: [wrinfo, channelinfo]
      description: Channel informations
      usage: |
             Example: /<command> Channel1
   wra:
      aliases: [wradmin]
      description: Channel admin commands
      usage: |
             Example: /<command> subcommand
   wrremove:
      aliases: [wrdelete]
      description: Remove a channel with all its signs!
      usage: |
             Example: /<command> subcommand
   wrlist:
      aliases: [channellist]
      description: Lists all channels!
      usage: |
             Example: /<command> page