Strings:
  ==: WirelessStrings
  chatTag: WirelessRedstone
  channelDoesNotExist: This channel doesn't exist!
  channelLocked: Channel locked !
  channelNameContainsInvalidCaracters: This channel name contains invalid caracters !
  channelRemovedCauseNoSign: Channel removed, no more signs in the worlds.
  channelUnlocked: Channel unlocked !
  commandForNextPage: /wr list pagenumber for next page!
  customizedLanguageSuccessfullyLoaded: You successfully loaded your customized language for Wireless Redstone! 
  forMoreInfosPerformWRInfo: To get more informations about a channel, perform /wr info <channel>.
  noItemOnPage: There are no items on this page!
  ownersOfTheChannelAre: The owners of this channel are
  pageNumberInferiorToZero: Page number cannot be inferior to 0!
  playerCannotCreateChannel: You are not allowed to create a channel.
  playerCannotCreateReceiverOnBlock: You cannot create a wireless receiver on this block !
  playerCannotCreateSign: You don't have the permission to create this sign!
  playerCannotDestroySign: You are not allowed to destroy this sign!
  playerCreatedChannel: You just created a new channel!
  playerDoesntHaveAccessToChannel: You don't have access to this channel.
  playerDoesntHavePermission: You don't have the permissions to do this.
  playerExtendedChannel: You just extended a channel!
  signDestroyed: Succesfully removed this sign !
  thisChannelContains: This channel contains
  tooFewArguments: Too few arguments !